#include "../../../Dino.h"
using namespace Dino;
bool test_reset();
bool test_setStretch();
bool test_returnDino();
bool test_returnCurrentFrame();
bool test_increaseFrame();
bool test_decreaseFrame();
bool test_setDead();
bool test_deadOrNot();
bool test_autoFrameChange();
bool test_setJump();
bool test_calculateGravity();
bool test_calculateCollipse();
bool test_calculateHp();
bool test_returnYSize();
bool test_returnXSize();
bool test_returnHScore();
bool test_setHScore();